ARG BASE_IMAGE=nvidia/cudagl:11.3.0-devel-ubuntu20.04
FROM $BASE_IMAGE

RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils \
	strace \
	&& rm -rf /var/lib/apt/lists/*
	
RUN python3 -m pip install --upgrade pip && \
	pip3 install numpy && \
	pip3 install msgpack-rpc-python && \
    pip3 install setuptools wheel && \
    pip3 install airsim

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser airsim_user sudo && \
	adduser airsim_user audio && \
	adduser airsim_user video

USER airsim_user
WORKDIR /home/airsim_user

RUN sudo chown -R airsim_user /home/airsim_user
