ARG BASE_IMAGE=osrf/ros:humble-desktop-full
FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	rsync \
    sudo \
    wget \
    x11-xserver-utils

COPY . /Colosseum

WORKDIR /Colosseum

# Install AirSim
RUN ./setup.sh && \
	./build.sh